name: Build

on: [push]

jobs:
  debian:
    name: Generate .deb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.1'
      - name: Generate fat JAR
        run: sbt assembly
      - run: mv dist/xemime.jar deb-package/usr/lib/xemime/xemime.jar
      - name: Generate min JRE
        run: |
          jlink --compress=2 \
            --module-path "${JAVA_HOME}\jmods" \
            --add-modules java.scripting,java.xml \
            --output deb-package/usr/lib/xemime/min-jre
      - run: chmod +x deb-package/usr/bin/xemime
      - run: dpkg-deb --build deb-package .
      - uses: actions/upload-artifact@v2
        with:
          name: debian
          path: '*.deb'
  windows:
    name: Generate installer for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.1'
      - name: Init sbt
        run: sbt version
        shell: bash
      - name: Generate fat JAR
        run: sbt assembly
      - name: Generate min JRE
        run: |
          jlink --compress=2 `
            --module-path "${JAVA_HOME}\jmods" `
            --add-modules java.scripting,java.xml `
            --output dist/min-jre
      - run: choco install innosetup
      - run: iscc windows/installer.iss
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: 'windows/Output/*'
