name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.1'
      - name: Generate fat JAR
        run: sbt assembly
      - run: jlink --compress=2 --module-path "${JAVA_HOME}\jmods" --add-modules java.base,java.scripting,java.xml --output dist/min-jre
      - run: ls dist
      - run: |
          mv dist/min-jre deb-package/usr/lib/xemime/min-jre
          mv dist/xemime.jar deb-package/usr/lib/xemime/xemime.jar
      - run: chmod +x deb-package/usr/bin/xemime
      - run: dpkg-deb --build deb-package .
      - uses: actions/upload-artifact@v2
        with:
          path: "*.deb"
