name: Generate .deb package

on: [push]

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x deb-package/usr/bin/xemime
      - run: dpkg-deb --build deb-package .
      - uses: actions/upload-artifact@v2
        with:
          path: "*.deb"
